[package]
name = "tinywasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
clap = "4.4.12"
log = "0.4.20"
num-derive = "0.4.1"
num-traits = "0.2.17"
thiserror = "1.0.52"
